### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by geg2102** [runtimed/runtimed#160]
Can you update docs to more accurately reflect the new api? Most of the structs used in the example (from 0.15.1) no longer exist on 0.22.0.

**Comment by rgbkrk** [comment]
I'm assuming you're taking about the `runtimelib` README, which definitely needs some changes now that I've broken out `jupyter_protocol` as a separate standalone that native ZeroMQ and Websocket clients can use to share types.

**Comment by geg2102** [comment]
> I'm assuming you're taking about the `runtimelib` README, which definitely needs some changes now that I've broken out `jupyter_protocol` as a separate standalone that native ZeroMQ and Websocket clients can use to share types.

Yes, exactly. Some of the old structs no longer exist, etc.

**Comment by rgbkrk** [comment]
Great, thank you. Started it off in https://github.com/runtimed/runtimed/pull/161

It really goes to show how little I've been touching the tokio side of this as I've done most of the buildout for GPUI/Zed.

**Comment by rgbkrk** [comment]
Looks like I also need to fix the fact that default features aren't around in order to fix `runtimelib`'s entry on docs.rs. https://docs.rs/crate/runtimelib/latest

I think I might have to just make async dispatcher be the default feature.

**Comment by rgbkrk** [comment]
Next time I ship I think this is good to go. I plan to ship with these updates after #147, including writing a README for `ollama-kernel`.

**Comment by rgbkrk** [comment]
Shipped! Thanks for posting about it.

https://docs.rs/runtimelib/0.23.0/runtimelib/

https://docs.rs/jupyter-protocol/latest/jupyter_protocol/
