### ISSUE TITLE
Deserialize wire messages into more concrete structs

### ISSUE THREAD

**Issue by cvaske** [runtimed/runtimed#24]
Currently the Serde structs for Jupyter messages are not deserialized very much, making object traversal code very verbose. The approach used in [kernel-sidecar-rs](https://github.com/kafonek/kernel-sidecar-rs/) uses more concrete Rust structs. We could use this as well.

* [message.rs](https://github.com/kafonek/kernel-sidecar-rs/blob/main/src/jupyter/message.rs)
* [header.rs](https://github.com/kafonek/kernel-sidecar-rs/blob/main/src/jupyter/header.rs)
* [metadata.rs](https://github.com/kafonek/kernel-sidecar-rs/blob/main/src/jupyter/metadata.rs)

**Comment by rgbkrk** [comment]
Done in #65, #62, #58.
